# Sets up one MT5 sync worker on a Windows VPS.
#
#   powershell -ExecutionPolicy Bypass -File setup-windows.ps1 `
#       -WorkerToken  "<the backend's MT5_WORKER_TOKEN>" `
#       -TerminalPath "C:\MT5\terminal1\terminal64.exe"
#
# It installs the Python dependencies into a private virtualenv, writes this
# worker's .env with an ACL that only Administrators can read, checks that the
# backend actually answers with this token, and registers a scheduled task so
# the worker comes back after a reboot.
#
# It does NOT install MetaTrader 5. That installer is interactive and each
# worker needs its OWN terminal directory, so those are made by hand once —
# see docs\mt5-vps-sync.md. This script refuses to continue if the terminal it
# is pointed at does not exist, rather than registering a task that can only
# fail.
#
# Re-running it is safe: it overwrites the .env and re-registers the task.

[CmdletBinding()]
param(
    # Must equal MT5_WORKER_TOKEN on the backend. This token can pull any
    # connected customer's investor password — treat it like a database
    # password, and do not paste it into a shared terminal.
    [Parameter(Mandatory = $true)]
    [string] $WorkerToken,

    # This worker's own MetaTrader 5 installation. Two workers sharing one
    # terminal directory cross each other's sessions.
    [Parameter(Mandatory = $true)]
    [string] $TerminalPath,

    [string] $ApiUrl = 'https://www.fxjournalpro.com/api/mt5',

    # Identifies this process in the logs and in the job record. Each worker on
    # the box needs a different one.
    [string] $WorkerId = 'vps1-terminal1',

    [int] $PollSeconds = 10,

    # Skip the scheduled task and just set the worker up to be run by hand.
    [switch] $NoService
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$venv = Join-Path $here '.venv'
$venvPython = Join-Path $venv 'Scripts\python.exe'
$envFile = Join-Path $here '.env'
$taskName = "FXJournalPro MT5 Worker ($WorkerId)"

function Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Ok($msg)   { Write-Host "    $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "    $msg" -ForegroundColor Yellow }

# ── 1. The terminal has to exist before anything else is worth doing ────────
Step 'Checking the MetaTrader 5 terminal'
if (-not (Test-Path -LiteralPath $TerminalPath)) {
    throw @"
No terminal at: $TerminalPath

Install MetaTrader 5 into its own directory for this worker, then point
-TerminalPath at its terminal64.exe. One installation per worker:

    C:\MT5\terminal1\terminal64.exe
    C:\MT5\terminal2\terminal64.exe
"@
}
Ok "Found $TerminalPath"

# ── 2. Python ───────────────────────────────────────────────────────────────
Step 'Checking Python'
$python = (Get-Command python -ErrorAction SilentlyContinue)
if (-not $python) { $python = (Get-Command py -ErrorAction SilentlyContinue) }
if (-not $python) {
    throw @"
Python was not found on PATH.

Install 64-bit Python 3.10 or newer from https://www.python.org/downloads/
and tick "Add python.exe to PATH" in the installer. The MetaTrader5 package
is 64-bit only — a 32-bit Python cannot talk to the terminal.
"@
}
$pyVersion = & $python.Source --version 2>&1
Ok "$pyVersion at $($python.Source)"

$bits = & $python.Source -c "import struct; print(struct.calcsize('P') * 8)"
if ("$bits".Trim() -ne '64') {
    throw "This Python is $bits-bit. The MetaTrader5 package needs 64-bit Python."
}
Ok '64-bit'

# ── 3. Dependencies, in a virtualenv of this worker's own ───────────────────
Step 'Installing dependencies'
if (-not (Test-Path -LiteralPath $venvPython)) {
    & $python.Source -m venv $venv
    if ($LASTEXITCODE -ne 0) { throw 'Could not create the virtualenv.' }
}
& $venvPython -m pip install --quiet --upgrade pip
& $venvPython -m pip install --quiet -r (Join-Path $here 'requirements.txt')
if ($LASTEXITCODE -ne 0) { throw 'pip install failed — see the output above.' }
Ok 'MetaTrader5 and requests installed'

# ── 4. This worker's .env ───────────────────────────────────────────────────
#
# Written with Set-Content -Encoding utf8 rather than a redirect, because the
# worker reads it as UTF-8 and the ANSI default mangles anything non-ASCII.
Step 'Writing .env'
@"
# Generated by setup-windows.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm').
# Never commit this file. It carries the worker token.
FXJP_API_URL=$ApiUrl
FXJP_WORKER_TOKEN=$WorkerToken
FXJP_WORKER_ID=$WorkerId
MT5_TERMINAL_PATH=$TerminalPath
FXJP_POLL_SECONDS=$PollSeconds
"@ | Set-Content -LiteralPath $envFile -Encoding utf8

# Strip inherited permissions and grant only SYSTEM and Administrators. The
# default on a VPS gives Users read access, and every connected customer's
# investor password is reachable with what is in this file.
icacls $envFile /inheritance:r /grant:r "SYSTEM:(R)" "BUILTIN\Administrators:(F)" | Out-Null
Ok "$envFile (readable only by Administrators)"

# ── 5. Does the backend actually accept this token? ─────────────────────────
#
# Worth doing now: a wrong token fails identically to a working one until a
# customer queues a job and nothing happens.
Step 'Testing the backend'
$claimUrl = "$($ApiUrl.TrimEnd('/'))/worker/claim"
try {
    # An empty body on purpose. Authentication is checked before the payload,
    # so 400 means the token was accepted and only the body was wrong.
    Invoke-RestMethod -Method Post -Uri $claimUrl `
        -Headers @{ Authorization = "Bearer $WorkerToken" } `
        -ContentType 'application/json' -Body '{}' -TimeoutSec 20 | Out-Null
    Ok 'Backend answered.'
} catch {
    $code = $null
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
    switch ($code) {
        400 { Ok 'Token accepted (400 on an empty body is expected).' }
        401 { throw "The backend rejected this token (401). FXJP_WORKER_TOKEN must equal MT5_WORKER_TOKEN on the server." }
        503 { throw "The backend has VPS sync switched off (503). Set MT5_VPS_SYNC_ENABLED=true and MT5_WORKER_TOKEN there, then redeploy." }
        404 { throw "No worker endpoint at $claimUrl. Check -ApiUrl; it should end in /api/mt5." }
        default { throw "Could not reach $claimUrl ($($_.Exception.Message))." }
    }
}

# ── 6. Survive a reboot ─────────────────────────────────────────────────────
if ($NoService) {
    Step 'Skipping the scheduled task (-NoService)'
} else {
    Step 'Registering the scheduled task'
    # AtLogOn, not AtStartup, and deliberately: MetaTrader 5 is a desktop
    # application and needs an interactive session. A task running as SYSTEM
    # lands in session 0 with no desktop, and the terminal never comes up. Set
    # the VPS to log this user in automatically and the worker starts with it.
    $action = New-ScheduledTaskAction -Execute $venvPython `
        -Argument "`"$(Join-Path $here 'mt5_worker.py')`"" -WorkingDirectory $here
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
        -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
        -Settings $settings -RunLevel Highest -Force | Out-Null
    Ok "Task `"$taskName`" runs at logon and restarts on failure."
    Warn 'MetaTrader needs a desktop session, so set this VPS to log on automatically.'
}

Write-Host "`nDone." -ForegroundColor Green
Write-Host "  Run now:   & `"$venvPython`" `"$(Join-Path $here 'mt5_worker.py')`""
if (-not $NoService) { Write-Host "  Or start:  Start-ScheduledTask -TaskName `"$taskName`"" }
Write-Host "  Logs:      the worker prints to stdout; redirect it if you want a file.`n"
